server:
  port: 10002
spring:
  application:
    name: auth
  redis:
    host: 112.124.110.204
    port: 6379
    password: Ftoul.com34%^
    database: 1
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制

eureka:
  client:
    service-url:
      defaultZone: http://localhost:50101/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
auth:
  jwt:
    secret: yinuo@Login(Auth}*^31)&tiannamen% # 登录校验的密钥
    pubKeyPath: /home/program/gxt_ssl/rsa.pub # 公钥地址
    priKeyPath: /home/program/gxt_ssl/rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: YN_TOKEN

