package com.inuol.entity.scenic;

public class AreaLabel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area_label.id
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area_label.scenic_area_id
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    private Long scenicAreaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area_label.scenic_label_id
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    private Long scenicLabelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area_label.id
     *
     * @return the value of t_area_label.id
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area_label.id
     *
     * @param id the value for t_area_label.id
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area_label.scenic_area_id
     *
     * @return the value of t_area_label.scenic_area_id
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    public Long getScenicAreaId() {
        return scenicAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area_label.scenic_area_id
     *
     * @param scenicAreaId the value for t_area_label.scenic_area_id
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    public void setScenicAreaId(Long scenicAreaId) {
        this.scenicAreaId = scenicAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area_label.scenic_label_id
     *
     * @return the value of t_area_label.scenic_label_id
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    public Long getScenicLabelId() {
        return scenicLabelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area_label.scenic_label_id
     *
     * @param scenicLabelId the value for t_area_label.scenic_label_id
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    public void setScenicLabelId(Long scenicLabelId) {
        this.scenicLabelId = scenicLabelId;
    }
}