package com.inuol.entity.scenic;

import java.util.Date;

public class Channel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.name
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.code
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.open_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private String openTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.url
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.state
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.create_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.update_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.creator
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Long creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.id
     *
     * @return the value of t_channel.id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.id
     *
     * @param id the value for t_channel.id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.name
     *
     * @return the value of t_channel.name
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.name
     *
     * @param name the value for t_channel.name
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.code
     *
     * @return the value of t_channel.code
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.code
     *
     * @param code the value for t_channel.code
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.open_time
     *
     * @return the value of t_channel.open_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public String getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.open_time
     *
     * @param openTime the value for t_channel.open_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setOpenTime(String openTime) {
        this.openTime = openTime == null ? null : openTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.url
     *
     * @return the value of t_channel.url
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.url
     *
     * @param url the value for t_channel.url
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.state
     *
     * @return the value of t_channel.state
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.state
     *
     * @param state the value for t_channel.state
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.create_time
     *
     * @return the value of t_channel.create_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.create_time
     *
     * @param createTime the value for t_channel.create_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.update_time
     *
     * @return the value of t_channel.update_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.update_time
     *
     * @param updateTime the value for t_channel.update_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.creator
     *
     * @return the value of t_channel.creator
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.creator
     *
     * @param creator the value for t_channel.creator
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }
}