package com.inuol.entity.scenic;

import java.util.Date;

public class HelpDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_help_detail.id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_help_detail.tourism_help_id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Long tourismHelpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_help_detail.question
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_help_detail.answer
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_help_detail.sort
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_help_detail.status
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_help_detail.create_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_help_detail.update_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_help_detail.creator
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Long creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_help_detail.id
     *
     * @return the value of t_help_detail.id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_help_detail.id
     *
     * @param id the value for t_help_detail.id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_help_detail.tourism_help_id
     *
     * @return the value of t_help_detail.tourism_help_id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Long getTourismHelpId() {
        return tourismHelpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_help_detail.tourism_help_id
     *
     * @param tourismHelpId the value for t_help_detail.tourism_help_id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setTourismHelpId(Long tourismHelpId) {
        this.tourismHelpId = tourismHelpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_help_detail.question
     *
     * @return the value of t_help_detail.question
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_help_detail.question
     *
     * @param question the value for t_help_detail.question
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_help_detail.answer
     *
     * @return the value of t_help_detail.answer
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_help_detail.answer
     *
     * @param answer the value for t_help_detail.answer
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_help_detail.sort
     *
     * @return the value of t_help_detail.sort
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_help_detail.sort
     *
     * @param sort the value for t_help_detail.sort
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_help_detail.status
     *
     * @return the value of t_help_detail.status
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_help_detail.status
     *
     * @param status the value for t_help_detail.status
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_help_detail.create_time
     *
     * @return the value of t_help_detail.create_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_help_detail.create_time
     *
     * @param createTime the value for t_help_detail.create_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_help_detail.update_time
     *
     * @return the value of t_help_detail.update_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_help_detail.update_time
     *
     * @param updateTime the value for t_help_detail.update_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_help_detail.creator
     *
     * @return the value of t_help_detail.creator
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_help_detail.creator
     *
     * @param creator the value for t_help_detail.creator
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }
}