package com.inuol.entity.scenic;

import java.util.Date;

public class RouteSet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_set.id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_set.route_id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Long routeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_set.site_name
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private String siteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_set.sort
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_set.create_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_set.update_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_set.creator
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Long creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_set.id
     *
     * @return the value of t_route_set.id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_set.id
     *
     * @param id the value for t_route_set.id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_set.route_id
     *
     * @return the value of t_route_set.route_id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Long getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_set.route_id
     *
     * @param routeId the value for t_route_set.route_id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setRouteId(Long routeId) {
        this.routeId = routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_set.site_name
     *
     * @return the value of t_route_set.site_name
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_set.site_name
     *
     * @param siteName the value for t_route_set.site_name
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName == null ? null : siteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_set.sort
     *
     * @return the value of t_route_set.sort
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_set.sort
     *
     * @param sort the value for t_route_set.sort
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_set.create_time
     *
     * @return the value of t_route_set.create_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_set.create_time
     *
     * @param createTime the value for t_route_set.create_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_set.update_time
     *
     * @return the value of t_route_set.update_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_set.update_time
     *
     * @param updateTime the value for t_route_set.update_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_set.creator
     *
     * @return the value of t_route_set.creator
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_set.creator
     *
     * @param creator the value for t_route_set.creator
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }
}