package com.inuol.entity.scenic;

import java.util.Date;

public class ScenicLabel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_label.id
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_label.label_name
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    private String labelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_label.state
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_label.create_time
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_label.update_time
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_label.creator
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    private Long creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_label.id
     *
     * @return the value of t_scenic_label.id
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_label.id
     *
     * @param id the value for t_scenic_label.id
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_label.label_name
     *
     * @return the value of t_scenic_label.label_name
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_label.label_name
     *
     * @param labelName the value for t_scenic_label.label_name
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName == null ? null : labelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_label.state
     *
     * @return the value of t_scenic_label.state
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_label.state
     *
     * @param state the value for t_scenic_label.state
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_label.create_time
     *
     * @return the value of t_scenic_label.create_time
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_label.create_time
     *
     * @param createTime the value for t_scenic_label.create_time
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_label.update_time
     *
     * @return the value of t_scenic_label.update_time
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_label.update_time
     *
     * @param updateTime the value for t_scenic_label.update_time
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_label.creator
     *
     * @return the value of t_scenic_label.creator
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_label.creator
     *
     * @param creator the value for t_scenic_label.creator
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }
}