package com.inuol.entity.scenic;

import java.util.Date;

public class ScenicSpot {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_spot.id
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_spot.scenic_area_id
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    private Long scenicAreaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_spot.name
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_spot.sort
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_spot.is_show
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    private String isShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_spot.create_time
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_spot.update_time
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_spot.state
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_spot.creator
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    private Long creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_spot.id
     *
     * @return the value of t_scenic_spot.id
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_spot.id
     *
     * @param id the value for t_scenic_spot.id
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_spot.scenic_area_id
     *
     * @return the value of t_scenic_spot.scenic_area_id
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    public Long getScenicAreaId() {
        return scenicAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_spot.scenic_area_id
     *
     * @param scenicAreaId the value for t_scenic_spot.scenic_area_id
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    public void setScenicAreaId(Long scenicAreaId) {
        this.scenicAreaId = scenicAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_spot.name
     *
     * @return the value of t_scenic_spot.name
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_spot.name
     *
     * @param name the value for t_scenic_spot.name
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_spot.sort
     *
     * @return the value of t_scenic_spot.sort
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_spot.sort
     *
     * @param sort the value for t_scenic_spot.sort
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_spot.is_show
     *
     * @return the value of t_scenic_spot.is_show
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_spot.is_show
     *
     * @param isShow the value for t_scenic_spot.is_show
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow == null ? null : isShow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_spot.create_time
     *
     * @return the value of t_scenic_spot.create_time
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_spot.create_time
     *
     * @param createTime the value for t_scenic_spot.create_time
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_spot.update_time
     *
     * @return the value of t_scenic_spot.update_time
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_spot.update_time
     *
     * @param updateTime the value for t_scenic_spot.update_time
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_spot.state
     *
     * @return the value of t_scenic_spot.state
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_spot.state
     *
     * @param state the value for t_scenic_spot.state
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_spot.creator
     *
     * @return the value of t_scenic_spot.creator
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_spot.creator
     *
     * @param creator the value for t_scenic_spot.creator
     *
     * @mbg.generated Wed Jan 22 14:35:20 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }
}