package com.inuol.entity.scenic;

import java.util.Date;

public class ScenicPhoto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_photo.id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_photo.scenic_area_id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Long scenicAreaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_photo.url
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_photo.like_num
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Integer likeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_photo.create_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_photo.update_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scenic_photo.creator
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Long creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_photo.id
     *
     * @return the value of t_scenic_photo.id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_photo.id
     *
     * @param id the value for t_scenic_photo.id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_photo.scenic_area_id
     *
     * @return the value of t_scenic_photo.scenic_area_id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Long getScenicAreaId() {
        return scenicAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_photo.scenic_area_id
     *
     * @param scenicAreaId the value for t_scenic_photo.scenic_area_id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setScenicAreaId(Long scenicAreaId) {
        this.scenicAreaId = scenicAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_photo.url
     *
     * @return the value of t_scenic_photo.url
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_photo.url
     *
     * @param url the value for t_scenic_photo.url
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_photo.like_num
     *
     * @return the value of t_scenic_photo.like_num
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Integer getLikeNum() {
        return likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_photo.like_num
     *
     * @param likeNum the value for t_scenic_photo.like_num
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_photo.create_time
     *
     * @return the value of t_scenic_photo.create_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_photo.create_time
     *
     * @param createTime the value for t_scenic_photo.create_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_photo.update_time
     *
     * @return the value of t_scenic_photo.update_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_photo.update_time
     *
     * @param updateTime the value for t_scenic_photo.update_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scenic_photo.creator
     *
     * @return the value of t_scenic_photo.creator
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scenic_photo.creator
     *
     * @param creator the value for t_scenic_photo.creator
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }
}