package com.inuol.entity.scenic;

import java.util.Date;

public class TourismHelp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tourism_help.id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tourism_help.question_type
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private String questionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tourism_help.sort
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tourism_help.state
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tourism_help.terminal
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private String terminal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tourism_help.create_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tourism_help.update_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tourism_help.creator
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    private Long creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tourism_help.id
     *
     * @return the value of t_tourism_help.id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tourism_help.id
     *
     * @param id the value for t_tourism_help.id
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tourism_help.question_type
     *
     * @return the value of t_tourism_help.question_type
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public String getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tourism_help.question_type
     *
     * @param questionType the value for t_tourism_help.question_type
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setQuestionType(String questionType) {
        this.questionType = questionType == null ? null : questionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tourism_help.sort
     *
     * @return the value of t_tourism_help.sort
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tourism_help.sort
     *
     * @param sort the value for t_tourism_help.sort
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tourism_help.state
     *
     * @return the value of t_tourism_help.state
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tourism_help.state
     *
     * @param state the value for t_tourism_help.state
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tourism_help.terminal
     *
     * @return the value of t_tourism_help.terminal
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public String getTerminal() {
        return terminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tourism_help.terminal
     *
     * @param terminal the value for t_tourism_help.terminal
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setTerminal(String terminal) {
        this.terminal = terminal == null ? null : terminal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tourism_help.create_time
     *
     * @return the value of t_tourism_help.create_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tourism_help.create_time
     *
     * @param createTime the value for t_tourism_help.create_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tourism_help.update_time
     *
     * @return the value of t_tourism_help.update_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tourism_help.update_time
     *
     * @param updateTime the value for t_tourism_help.update_time
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tourism_help.creator
     *
     * @return the value of t_tourism_help.creator
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tourism_help.creator
     *
     * @param creator the value for t_tourism_help.creator
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }
}