package com.inuol.entity.scenic;

import java.util.Date;

public class Vr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vr.id
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vr.scenic_spot_id
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    private Long scenicSpotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vr.url
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vr.description
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vr.create_time
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vr.update_time
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vr.creator
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    private Long creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vr.id
     *
     * @return the value of t_vr.id
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vr.id
     *
     * @param id the value for t_vr.id
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vr.scenic_spot_id
     *
     * @return the value of t_vr.scenic_spot_id
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    public Long getScenicSpotId() {
        return scenicSpotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vr.scenic_spot_id
     *
     * @param scenicSpotId the value for t_vr.scenic_spot_id
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    public void setScenicSpotId(Long scenicSpotId) {
        this.scenicSpotId = scenicSpotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vr.url
     *
     * @return the value of t_vr.url
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vr.url
     *
     * @param url the value for t_vr.url
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vr.description
     *
     * @return the value of t_vr.description
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vr.description
     *
     * @param description the value for t_vr.description
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vr.create_time
     *
     * @return the value of t_vr.create_time
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vr.create_time
     *
     * @param createTime the value for t_vr.create_time
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vr.update_time
     *
     * @return the value of t_vr.update_time
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vr.update_time
     *
     * @param updateTime the value for t_vr.update_time
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vr.creator
     *
     * @return the value of t_vr.creator
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vr.creator
     *
     * @param creator the value for t_vr.creator
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }
}