server:
  port: 10010
spring:
  redis:
    host: 112.124.110.204
    port: 6379
    password: Ftoul.com34%^
    database: 1
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
  zipkin:
       #zipkin中心地址
    base-url: http://localhost:9411
       #发送数据类型 kafaka、rabbitmq、web
    sender:
        type: web
    sleuth:
      sampler:
        probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:50101/eureka
    registry-fetch-interval-seconds: 5
zuul:
  #prefix: /api
  prefix: /api
  routes:
    user: /user/** #路由到user微服务
    auth: /auth/** #路由到auth微服务
    strategy: /strategy/**
    bigdatasystem: /bigdatasystem/** #路由到大数据系统管理模块
    yinuo-upload: /yinuo-upload/** #路由到文件上传微服务
    yinuo-appointment: /yinuo-appointment/** #路由到预约管理微服务
    yinuo-manage: /yinuo-manage/** #路由到中台管理微服务
  add-host-header: true
  sensitiveHeaders: #默认zuul会屏蔽cookie，cookie不会传到下游服务，这里设置为空则取消默认的黑名单，如果设置了具体的头信息则不会传到下游服务
  host:
    max-total-connections: 10000
    max-per-route-connections: 10000
  semaphore:
    max-semaphores: 200
  #zuul 统一异常处理相关 暂未启用 先保留
  #SendErrorFilter:
  #  error:
  #    disable: true
  #网关限流配置
  #ratelimit:
              #key-prefix: ZUUL-LIMIT  #对应用来标识请求的key的前缀
              #enabled: true
              #repository: REDIS  #对应存储类型（用来存储统计信息）
              #behind-proxy: true  #代理之后
              #add-response-headers: true
              #default-policy-list: #可选 - 针对所有的路由配置的策略，除非特别配置了policies
                 #- limit: 2 #可选 - 每个刷新时间窗口对应的请求数量限制
                  # quota: 5 #可选-  每个刷新时间窗口对应的请求时间限制（秒）
                   #refresh-interval: 5 # 刷新时间窗口的时间，默认值 (秒)
                   #type: #可选 限流方式
                          #- origin
              #policy-list:
               #     strategy: #特定的路由
                #          - limit: 2 #可选- 每个刷新时间窗口对应的请求数量限制
                 #           quota: 3   #可选-  每个刷新时间窗口对应的请求时间限制（秒）
                  #          refresh-interval: 3 # 刷新时间窗口的时间，默认值 (秒)
                   #         type: #可选 限流方式
                    #            - url=/api/strategy/travel/list
                     #           - origin


ribbon:
  ConnectTimeout: 10000  #请求连接的超时时间
  ReadTimeout: 10000 #请求处理的超时时间
  eager-load:
    enabled: true

yinuo:
  jwt:
    pubKeyPath: D:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: YN_TOKEN
  filter:
    allowPaths:
      - /api/auth/login
      - /api/auth/registerUser
      - /api/auth/getCode
      - /api/strategy/travel/list # 旅游攻略列表
      - /api/strategy/travel/detail # 旅游攻略详情
      - /api/strategy/travel/commentList # 旅游攻略评论列表
      - /api/yinuo-manage/manageController/getBannerList_manage
      - /api/yinuo-upload/uploadMulti
      - /api/strategy/v2/api-docs
      - /api/user/v2/api-docs
      - /api/auth/v2/api-docs
      - /api/bigdatasystem/v2/api-docs
      - /api/yinuo-upload/v2/api-docs
      - /api/yinuo-appointment/v2/api-docs
      - /api/yinuo-manage/v2/api-docs
      
      


