logging: 
   #path: C:\\Users\\Administrator\\Desktop\\logs
   file: logs/${spring.cloud.config.name}.log
   level:
    root: info
    com.ark.hngxt.product: info
    com.ark.dependencies.common: debug
    
rabbitmq:
  HTTP_ENDPOINT: http://1207840059439746.mqrest.cn-hangzhou.aliyuncs.com
  ACCESS_KEY: LTAI4FvHzgcuGarjG8ywQ5ZS
  SECRET_KEY: GPeKyWj6PrZuXPtptcNKehNwXHyr0u
  topic:
    ark_common: ark_common_dev
    ark_common_callback: ark_common_callback_dev
     
spring:
   datasource:
      url: jdbc:mysql://192.168.100.234:3306/com_ark_hngxt_product?useUnicode=true&characterEncoding=UTF8&noAccessToProcedureBodies=true&allowMultiQueries=true
      username: hngxt_prod_user
      password: inuol_product
      driverClassName: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
      # 连接池配置
      hikari: 
        pool-name: HikariPool
        minimum-idle: 10
        maximum-pool-size: 100
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
#属性配置请先执行: CREATE DATABASE IF NOT EXISTS com_ark_hngxt_product CHARSET=utf8;            
---
spring:
  redis:
    host: 192.168.100.190
    port: 6379
    password: Ftoul.com34%^
    database: 0
    timeout: 5000
    lettuce:
      pool:
        max-active: 32
        max-wait: 30ms
        max-idle: 16
        min-idle: 8

authsettings: 
   tokenExpirePeriod: 43200000 #单位 ms 5天
   privateKey: 
   publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq7eGIL++tTXwBkG2nwRs\
   gII3tNE6yO0BkYH9qg0hu7Oy2dIQ/ZOPLrP5oh8RMp6m2rBSzOtUUDZ1iSKA4g8Y\
   ynKtzbYmG7kZudsyPkDUqj7oDZm81yhhiHUdnBNZD6fWBRQ0K91r67vJuNtxNYTW\
   /u5uXmdio8hbkrusSii7A64aTaQdjC/p/PA35T9mbHao2f0L377QAE1GyS5T3TTZ\
   Ufpc9n36ap0lQTaN73NPgNaGNaZPREKWkLslON9JqyrA8Fv8rWzoX0t7iqRPNF4l\
   IeseIdNmpaQdEYUcthYJPpkmXUxdsMuDdJmLmx2sGnoxhzfr37P5fz741FfPNmOg\
   EQIDAQAB"
   tokenMetaName: x-auth-token-meta
   tokenUserName: x-auth-token
   tokenSignName: x-auth-token-sign
   tokenParameterName: access_resouce_token
   tokenName: x-auth-token
   tokenIssuer: com.ark
   free-urls:
   - path: /swagger-ui.html
     method: GET
   - path: /v2/api-docs
     method: GET
   - path: /swagger-resources/**
     method: GET
   - path: /error
     method: GET,POST
   - path: /webjars/**
     method: GET
   - path: /doc.html
     method: GET
   - path: /swagger-bootstrap-ui.html
     method: GET    
   - path: /test/**  #出错才能访问CustomErrorController
     method: GET,POST 
   - path: /free/**  
     method: GET,POST,PUT,PATCH,DELETE           
   disableTokenValidation: true
   innerTokenValidationUrls:
   - path: /test2/validate
     method: PUT,DELETE            