logging: 
   #path: C:\\Users\\Administrator\\Desktop\\logs
   file: /home/data/logs/ark/product/${spring.cloud.config.name}.log
   level:
    root: info
    com.ark.hngxt.product: info
    com.ark.dependencies.common: debug
    
rabbitmq:
  HTTP_ENDPOINT: http://1207840059439746.mqrest.cn-hangzhou.aliyuncs.com
  ACCESS_KEY: LTAI4FvHzgcuGarjG8ywQ5ZS
  SECRET_KEY: GPeKyWj6PrZuXPtptcNKehNwXHyr0u
  topic:
    ark_common: ark_common
    ark_common_callback: ark_common_callback
    
spring:
   datasource:
      url: jdbc:mysql://rm-bp13ng0zwo0972u6235970.mysql.rds.aliyuncs.com:3306/com_ark_hngxt_product?useUnicode=true&characterEncoding=UTF8&noAccessToProcedureBodies=true&allowMultiQueries=true
      username: hngxt
      password: Inuol@2020$$
      driverClassName: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
      # 连接池配置
      hikari: 
        pool-name: HikariPool
        minimum-idle: 10
        maximum-pool-size: 100
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
#属性配置请先执行: CREATE DATABASE IF NOT EXISTS com_ark_hngxt_product CHARSET=utf8;    
 
         
   
authsettings: 
   tokenExpirePeriod: 43200000 #单位 ms 5天
   privateKey: 
   publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvu9smAmPATKH7Gy32gFO\
   ugQSuliksqwheRv1cxPEk32n/DILl03SoG+wboUGPLtYQr0/D/wiT23Qp9nP52Tq\
   Kg+V3E6YhuUYOi1uCBgLnKxPh4vACkpQffwWyYmrvo2SbqzqSX0CnkX4RBhY8fXX\
   kungkjP+YWTbxsd4PwUvg6PfchJ6A2JedlEs1KmSalWsMvy2CkEO56pjqYzEgufJ\
   Ek6sPGMBHj65uUlVmUbuZZR94kNZwm4xeY7OszYYmzKs9bl3EzVQ51BBvWFsF6nX\
   4EXVJ846vLoyeDPxvFpwnz8LxYwm55ER7xaqIttija3wKEdLzaM23PuOnGOpfJDB\
   LQIDAQAB"
   tokenMetaName: x-auth-token-meta
   tokenUserName: x-auth-token
   tokenSignName: x-auth-token-sign
   tokenParameterName: access_resouce_token
   tokenName: x-auth-token
   tokenIssuer: com.ark
   free-urls:
   - path: /swagger-ui.html
     method: GET
   - path: /v2/api-docs
     method: GET
   - path: /swagger-resources/**
     method: GET
   - path: /error
     method: GET,POST
   - path: /webjars/**
     method: GET
   - path: /doc.html
     method: GET
   - path: /swagger-bootstrap-ui.html
     method: GET    
   - path: /test/**  #出错才能访问CustomErrorController
     method: GET,POST
   - path: /free/**  
     method: GET,POST,PUT,PATCH,DELETE            
   disableTokenValidation: true
   innerTokenValidationUrls:
   - path: /test2/validate
     method: PUT,DELETE            