server: 
  port: 6140

spring:
  profiles:
    active:
    - ${spring.cloud.config.profile}
  application:
    name: com-ark-hngxt-product
--- 
spring:
  jackson:
    time-zone: GMT+8
    date-format: "yyyy-MM-dd HH:mm:ss"
  http:
   encoding:
    charset: utf-8
    enabled: true
    force: true    
        
swagger:
   api-info:
      version: "0.0.1"
      title: "接口文档"
      description: "接口支持"
      termsOfServiceUrl:
      license:
      licenseUrl: ""
      contactName: "壹诺科技-技术部"
      contactUrl: "https://www.inuol.com/"
      contactEmail: "develop@inuol.com"
      
mybatis-plus:
  mapper-locations: classpath:com/ark/hngxt/product/mapper/xml/*.xml
  typeAliasesPackage: com/ark/hngxt/product/domain
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
    local-cache-scope: statement  
    
        