package com.yinuo.scenic.mapper;

import com.inuol.entity.scenic.AreaLabel;
import com.inuol.entity.scenic.AreaLabelCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AreaLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    long countByExample(AreaLabelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    int deleteByExample(AreaLabelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    int insert(AreaLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    int insertSelective(AreaLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    List<AreaLabel> selectByExample(AreaLabelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    AreaLabel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") AreaLabel record, @Param("example") AreaLabelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    int updateByExample(@Param("record") AreaLabel record, @Param("example") AreaLabelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    int updateByPrimaryKeySelective(AreaLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    int updateByPrimaryKey(AreaLabel record);



    int selectCountByScenicAreaId(long scenicAreaId);
}