package com.yinuo.scenic.mapper;

import com.inuol.entity.scenic.Channel;
import com.inuol.entity.scenic.ChannelCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    long countByExample(ChannelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int deleteByExample(ChannelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int insert(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int insertSelective(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    List<Channel> selectByExample(ChannelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    Channel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") Channel record, @Param("example") ChannelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByExample(@Param("record") Channel record, @Param("example") ChannelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByPrimaryKeySelective(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByPrimaryKey(Channel record);
}