package com.yinuo.scenic.mapper;

import com.inuol.entity.scenic.HelpDetail;
import com.inuol.entity.scenic.HelpDetailCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HelpDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_help_detail
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    long countByExample(HelpDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_help_detail
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int deleteByExample(HelpDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_help_detail
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_help_detail
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int insert(HelpDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_help_detail
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int insertSelective(HelpDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_help_detail
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    List<HelpDetail> selectByExample(HelpDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_help_detail
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    HelpDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_help_detail
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") HelpDetail record, @Param("example") HelpDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_help_detail
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByExample(@Param("record") HelpDetail record, @Param("example") HelpDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_help_detail
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByPrimaryKeySelective(HelpDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_help_detail
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByPrimaryKey(HelpDetail record);
}