package com.yinuo.scenic.mapper;

import com.inuol.entity.scenic.Route;
import com.inuol.entity.scenic.RouteCriteria;
import com.inuol.vo.scenic.RouteResult;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface RouteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    long countByExample(RouteCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int deleteByExample(RouteCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int insert(Route record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int insertSelective(Route record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    List<Route> selectByExample(RouteCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    Route selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") Route record, @Param("example") RouteCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByExample(@Param("record") Route record, @Param("example") RouteCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByPrimaryKeySelective(Route record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByPrimaryKey(Route record);

    /**
     * 自定义查询所有路线
     * @return
     */
    List<RouteResult> selectAll(@Param("routeName") String routeName);

    /**
     * 判断路线名称是否重复
     * @param routeName
     * @return
     */
    int judgeRepeatByRouteName(String routeName);


    /**
     * 判断路线名称是否重复,除去自己
     * @param map
     * @return
     */
    int judgeRepeatByRouteNameExceptOwn(Map<String,Object> map);
}