package com.yinuo.scenic.mapper;

import com.inuol.entity.scenic.RouteSet;
import com.inuol.entity.scenic.RouteSetCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RouteSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_set
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    long countByExample(RouteSetCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_set
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int deleteByExample(RouteSetCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_set
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_set
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int insert(RouteSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_set
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int insertSelective(RouteSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_set
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    List<RouteSet> selectByExample(RouteSetCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_set
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    RouteSet selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_set
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") RouteSet record, @Param("example") RouteSetCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_set
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByExample(@Param("record") RouteSet record, @Param("example") RouteSetCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_set
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByPrimaryKeySelective(RouteSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_set
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByPrimaryKey(RouteSet record);

    /**
     *
     * @param routeId
     * @return
     */
    int deleteByRouteId(@Param("routeId") Long routeId);
}