package com.yinuo.scenic.mapper;

import com.inuol.entity.scenic.ScenicLabel;
import com.inuol.entity.scenic.ScenicLabelCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ScenicLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    long countByExample(ScenicLabelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    int deleteByExample(ScenicLabelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    int insert(ScenicLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    int insertSelective(ScenicLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    List<ScenicLabel> selectByExample(ScenicLabelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    ScenicLabel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") ScenicLabel record, @Param("example") ScenicLabelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    int updateByExample(@Param("record") ScenicLabel record, @Param("example") ScenicLabelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    int updateByPrimaryKeySelective(ScenicLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_label
     *
     * @mbg.generated Tue Feb 11 11:34:32 CST 2020
     */
    int updateByPrimaryKey(ScenicLabel record);

    int selectCountByLabelName(String labelName);
}