package com.yinuo.scenic.mapper;

import com.inuol.entity.scenic.ScenicArea;
import com.inuol.entity.scenic.ScenicAreaCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScenicAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_area
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    long countByExample(ScenicAreaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_area
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int deleteByExample(ScenicAreaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_area
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_area
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int insert(ScenicArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_area
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int insertSelective(ScenicArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_area
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    List<ScenicArea> selectByExample(ScenicAreaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_area
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    ScenicArea selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_area
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") ScenicArea record, @Param("example") ScenicAreaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_area
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByExample(@Param("record") ScenicArea record, @Param("example") ScenicAreaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_area
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByPrimaryKeySelective(ScenicArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_area
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByPrimaryKey(ScenicArea record);
}