package com.yinuo.scenic.mapper;

import java.util.List;

import com.inuol.entity.scenic.ScenicPhoto;
import com.inuol.entity.scenic.ScenicPhotoCriteria;
import org.apache.ibatis.annotations.Param;

public interface ScenicPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_photo
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    long countByExample(ScenicPhotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_photo
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int deleteByExample(ScenicPhotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_photo
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_photo
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int insert(ScenicPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_photo
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int insertSelective(ScenicPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_photo
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    List<ScenicPhoto> selectByExample(ScenicPhotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_photo
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    ScenicPhoto selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_photo
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") ScenicPhoto record, @Param("example") ScenicPhotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_photo
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByExample(@Param("record") ScenicPhoto record, @Param("example") ScenicPhotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_photo
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByPrimaryKeySelective(ScenicPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_photo
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByPrimaryKey(ScenicPhoto record);
}