package com.yinuo.scenic.mapper;


import com.inuol.entity.scenic.ScenicSpot;
import com.inuol.entity.scenic.ScenicSpotCriteria;
import com.yinuo.common.common.HttpResult;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface ScenicSpotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_spot
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    long countByExample(ScenicSpotCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_spot
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int deleteByExample(ScenicSpotCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_spot
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_spot
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int insert(ScenicSpot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_spot
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int insertSelective(ScenicSpot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_spot
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    List<ScenicSpot> selectByExample(ScenicSpotCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_spot
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    ScenicSpot selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_spot
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") ScenicSpot record, @Param("example") ScenicSpotCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_spot
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByExample(@Param("record") ScenicSpot record, @Param("example") ScenicSpotCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_spot
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByPrimaryKeySelective(ScenicSpot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scenic_spot
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByPrimaryKey(ScenicSpot record);


    List<ScenicSpot> selectByScenicAreaId(Long scenicAreaId);
    List<ScenicSpot> selectByName(String name);
    List<ScenicSpot> selectByScenicAreaIdAndName(Map<String, Object> map);
    List<ScenicSpot> selectAll();
}