package com.yinuo.scenic.mapper;

import com.inuol.entity.scenic.TourismHelp;
import com.inuol.entity.scenic.TourismHelpCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TourismHelpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tourism_help
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    long countByExample(TourismHelpCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tourism_help
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int deleteByExample(TourismHelpCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tourism_help
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tourism_help
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int insert(TourismHelp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tourism_help
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int insertSelective(TourismHelp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tourism_help
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    List<TourismHelp> selectByExample(TourismHelpCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tourism_help
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    TourismHelp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tourism_help
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") TourismHelp record, @Param("example") TourismHelpCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tourism_help
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByExample(@Param("record") TourismHelp record, @Param("example") TourismHelpCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tourism_help
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByPrimaryKeySelective(TourismHelp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tourism_help
     *
     * @mbg.generated Fri Jan 17 10:01:37 CST 2020
     */
    int updateByPrimaryKey(TourismHelp record);
}