package com.yinuo.scenic.mapper;

import com.inuol.entity.scenic.Vr;
import com.inuol.entity.scenic.VrCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vr
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    long countByExample(VrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vr
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    int deleteByExample(VrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vr
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vr
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    int insert(Vr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vr
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    int insertSelective(Vr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vr
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    List<Vr> selectByExample(VrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vr
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    Vr selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vr
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") Vr record, @Param("example") VrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vr
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    int updateByExample(@Param("record") Vr record, @Param("example") VrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vr
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    int updateByPrimaryKeySelective(Vr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vr
     *
     * @mbg.generated Wed Jan 22 15:29:46 CST 2020
     */
    int updateByPrimaryKey(Vr record);

    int selectCountByScenicSpotId(long scenicSpotId);

}