server:
  port: 10005
#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.29.175.45:3306/strategy?useSSL=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: square2019
    password: square@2019$$
  redis:
      host: 112.124.110.204
      port: 6379
      password: Ftoul.com34%^
      database: 1
      jedis:
        pool:
          maxActive: 3
          maxIdle: 3
          minIdle: 1
          maxWait: -1 #连接池最大等行时间 -1没有限制
  zipkin:
       #zipkin中心地址
    base-url: http://localhost:9411
       #发送数据类型 kafaka、rabbitmq、web
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address:  127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id

