

eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address:  127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id
    
fdfs:
  so-timeout: 1501
  connect-timeout: 601 
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  pool:
    max-total: 20  #从池中借出的对象的最大数目（配置为-1表示不限制）
    max-wait-millis: 5000  #获取连接时的最大等待毫秒数(默认配置为5秒)
    max-total-per-key: 50  #每个key最大连接数
    max-idle-per-key: 10  #每个key对应的连接池最大空闲连接数
    max_idle_per_key: 5  #每个key对应的连接池最小空闲连接数
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.100.191:22122

fdfsClientUrl: http://tfs.inuol.com/
fileTemp: D:\home\fileTemp
