spring:
  application:
    name: welfare #指定服务名
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  ###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/yinuo/welfare/mapper/xml/*.xml
  typeAliasesPackage: com.inuol.entity.welfare
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true #驼峰命令
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
    local-cache-scope: statement

    ############# 分页插件PageHelper配置 #############
pagehelper:
    #标识是哪一种数据库
    helper-dialect: mysql
    #启用合理化，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
    reasonable: false
    support-methods-arguments: true
    #如果 pageSize=0 就会查询出全部的结果（相当于没有执行分页查询）
    pageSizeZero: true
    #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值，
    #可以配置pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值，
    #默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
    params: count=countSql
    #支持通过 Mapper 接口参数来传递分页参数，默认值false，
    #分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
    supportMethodsArguments: true

