package com.inuol.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.mobile
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    private Integer mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.name
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id_type
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    private String idType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id_card
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.sex
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.regist_channel
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    private String registChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.regist_date
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    private Date registDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.be_auth
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    private Boolean beAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.state
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    private Boolean state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.logo
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.create_date
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.city
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.birth_day
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    private String birthDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.update_date
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.mobile
     *
     * @return the value of t_user.mobile
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public Integer getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.mobile
     *
     * @param mobile the value for t_user.mobile
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.name
     *
     * @return the value of t_user.name
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.name
     *
     * @param name the value for t_user.name
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id_type
     *
     * @return the value of t_user.id_type
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public String getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id_type
     *
     * @param idType the value for t_user.id_type
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public void setIdType(String idType) {
        this.idType = idType == null ? null : idType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id_card
     *
     * @return the value of t_user.id_card
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id_card
     *
     * @param idCard the value for t_user.id_card
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.sex
     *
     * @return the value of t_user.sex
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.sex
     *
     * @param sex the value for t_user.sex
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.regist_channel
     *
     * @return the value of t_user.regist_channel
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public String getRegistChannel() {
        return registChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.regist_channel
     *
     * @param registChannel the value for t_user.regist_channel
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public void setRegistChannel(String registChannel) {
        this.registChannel = registChannel == null ? null : registChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.regist_date
     *
     * @return the value of t_user.regist_date
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public Date getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.regist_date
     *
     * @param registDate the value for t_user.regist_date
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.be_auth
     *
     * @return the value of t_user.be_auth
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public Boolean getBeAuth() {
        return beAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.be_auth
     *
     * @param beAuth the value for t_user.be_auth
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public void setBeAuth(Boolean beAuth) {
        this.beAuth = beAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.state
     *
     * @return the value of t_user.state
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.state
     *
     * @param state the value for t_user.state
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.logo
     *
     * @return the value of t_user.logo
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.logo
     *
     * @param logo the value for t_user.logo
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.create_date
     *
     * @return the value of t_user.create_date
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.create_date
     *
     * @param createDate the value for t_user.create_date
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.city
     *
     * @return the value of t_user.city
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.city
     *
     * @param city the value for t_user.city
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.birth_day
     *
     * @return the value of t_user.birth_day
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public String getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.birth_day
     *
     * @param birthDay the value for t_user.birth_day
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public void setBirthDay(String birthDay) {
        this.birthDay = birthDay == null ? null : birthDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.update_date
     *
     * @return the value of t_user.update_date
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.update_date
     *
     * @param updateDate the value for t_user.update_date
     *
     * @mbg.generated Thu Dec 26 16:17:33 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}