#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.29.175.45:3306/square?useUnicode=true&characterEncoding=UTF8&noAccessToProcedureBodies=true&allowMultiQueries=true
    username: square2019
    password: square@2019$$
  redis:
    host: 112.124.110.204
    port: 6379
    password: Ftoul.com34%^
    database: 1
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
  ###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath:com/yinuo/framework/mapper/xml/*.xml
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
    local-cache-scope: statement

eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address:  127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id
    
    
auth:
  jwt:
    secret: yinuo@Login(Auth}*^31)&tiannamen% # 登录校验的密钥
    pubKeyPath: D:\tmp\rsa\rsa.pub # 公钥地址
    priKeyPath: D:\tmp\rsa\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: YN_TOKEN