package com.inuol.entity.backstageAuth;

import java.util.Date;

public class Auth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.id
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.parent_id
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.auth_code
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    private String authCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.auth_text
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    private String authText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.url
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.create_time
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.update_time
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.creator
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.node_type
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    private String nodeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.sort_id
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    private Integer sortId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.id
     *
     * @return the value of t_auth.id
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.id
     *
     * @param id the value for t_auth.id
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.parent_id
     *
     * @return the value of t_auth.parent_id
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.parent_id
     *
     * @param parentId the value for t_auth.parent_id
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.auth_code
     *
     * @return the value of t_auth.auth_code
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.auth_code
     *
     * @param authCode the value for t_auth.auth_code
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public void setAuthCode(String authCode) {
        this.authCode = authCode == null ? null : authCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.auth_text
     *
     * @return the value of t_auth.auth_text
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public String getAuthText() {
        return authText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.auth_text
     *
     * @param authText the value for t_auth.auth_text
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public void setAuthText(String authText) {
        this.authText = authText == null ? null : authText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.url
     *
     * @return the value of t_auth.url
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.url
     *
     * @param url the value for t_auth.url
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.create_time
     *
     * @return the value of t_auth.create_time
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.create_time
     *
     * @param createTime the value for t_auth.create_time
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.update_time
     *
     * @return the value of t_auth.update_time
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.update_time
     *
     * @param updateTime the value for t_auth.update_time
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.creator
     *
     * @return the value of t_auth.creator
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.creator
     *
     * @param creator the value for t_auth.creator
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.node_type
     *
     * @return the value of t_auth.node_type
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public String getNodeType() {
        return nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.node_type
     *
     * @param nodeType the value for t_auth.node_type
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public void setNodeType(String nodeType) {
        this.nodeType = nodeType == null ? null : nodeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.sort_id
     *
     * @return the value of t_auth.sort_id
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.sort_id
     *
     * @param sortId the value for t_auth.sort_id
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }
}