package com.inuol.entity.backstageAuth;

public class RoleAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_auth.id
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_auth.role_id
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_auth.auth_id
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    private Long authId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_auth.id
     *
     * @return the value of t_role_auth.id
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_auth.id
     *
     * @param id the value for t_role_auth.id
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_auth.role_id
     *
     * @return the value of t_role_auth.role_id
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_auth.role_id
     *
     * @param roleId the value for t_role_auth.role_id
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_auth.auth_id
     *
     * @return the value of t_role_auth.auth_id
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public Long getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_auth.auth_id
     *
     * @param authId the value for t_role_auth.auth_id
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    public void setAuthId(Long authId) {
        this.authId = authId;
    }
}