server:
  port: 8085

#数据库配置
spring:
  application:
    name: yinuo-scenic #指定服务名
  profiles:
    active: test

  zipkin:
    #zipkin中心地址
    base-url: http://localhost:9411
    #发送数据类型 kafaka、rabbitmq、web
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
