package com.yinuo.backstageAuth.mapper;

import com.inuol.entity.backstageAuth.RoleAuth;
import com.inuol.entity.backstageAuth.RoleAuthCriteria;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface RoleAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    long countByExample(RoleAuthCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    int deleteByExample(RoleAuthCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    int insert(RoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    int insertSelective(RoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    List<RoleAuth> selectByExample(RoleAuthCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    RoleAuth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") RoleAuth record, @Param("example") RoleAuthCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    int updateByExample(@Param("record") RoleAuth record, @Param("example") RoleAuthCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    int updateByPrimaryKeySelective(RoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbg.generated Fri Jan 17 11:49:44 CST 2020
     */
    int updateByPrimaryKey(RoleAuth record);

    /**
     * 批量添加
     * @param roleAuthVoList
     * @return
     */
    //int insertBatch(List<RoleAuthVo> roleAuthVoList);


    /**
     * 根据角色id 删除角色权限
     * @param roleId
     * @return
     */
    int deleteByRoleId(Long roleId);


    List<Long> selectAuthIdByRoleId(String roleId);


}